services:
    redis:
        image: redis:8-alpine
        container_name: redis
        ports:
            - "6379:6379"
        command: ["redis-server", "--save", "", "--appendonly", "no"]
        
    matching-service:
        build: ./matching-service
        container_name: matching-service
        ports:
            - "8080:8080"
        depends_on:
            - redis